### ISSUE TITLE
Undefined Moderator variable in ModeratorController:76

### ISSUE THREAD

**Issue by jopcode** [tooinfinity/magapos#31]
I guess this shouldn't be like that, and you shouldn't pass any "moderator" variable, would you?

**ModeratorController:**
```
public function create()
    {
        return view('dashboard.moderator.create', compact('moderator'));
    }
```

**Comment by tooinfinity** [comment]
ohhhh yes this's my mistake , you are right i don't need to pass that .
thank you for your participate and i will fix it .
